import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect } from 'react'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {Blog,Footer,Header,Navbar,Title,Pagination} from '../components'
import {fetchdata} from '../api'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() => {
    getdata()
  },)
  const getdata=()=>{
    fetchdata("/api/articles/?populate=*").then(res =>console.log(res))
  }
  
  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Nav Bar Started */}
      <Navbar/>
      {/* Navbar Ended */}

      {/* Blog section Started */}
      <Blog/>
      {/* Blog section Ended */}
      {/* pagination started  */}
      
      <Pagination/>


      {/* Pagination Ended */}
      {/* cta started */}
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
            <h1 className="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Slow-carb next level shoindxgoitch ethical authentic, scenester sriracha forage.</h1>
            <button className="flex-shrink-0 text-white bg-red-500 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded text-lg mt-10 sm:mt-0">Subscribe</button>
          </div>
        </div>
      </section>
      {/* cta ended */}
      
      {/* footer section started */}
      <Footer/>
      {/* footer section Ended  */}
    </>
  )
}
